const STORAGE_KEY = "kompetenzraster-data-v1";
const demo = {
  schemaVersion: 1,
  title: "Kompetenzraster",
  levels: [{ id: "level-1", name: "Level 1" }, { id: "level-2", name: "Level 2" }, { id: "level-3", name: "Level 3" }],
  areas: [{ id: "area-1", name: "Neue Kompetenzbereiche hier anlegen" }],
  competencies: []
};
let data = loadData();
let draggedId = null;
let dependencySelection = null;
let dependencyPreviewId = null;
let showDependencies = false;
let presentationMode = false;
let presentationLocked = false;
let fileDragDepth = 0;
let drawFrame = null;
const $ = id => document.getElementById(id);

function uid(prefix) { return `${prefix}-${crypto.randomUUID()}`; }
function loadData() { try { const saved = localStorage.getItem(STORAGE_KEY); return saved ? normalize(JSON.parse(saved)) : structuredClone(demo); } catch { return structuredClone(demo); } }
function normalize(value) {
  const next = value && typeof value === "object" ? value : structuredClone(demo);
  next.levels = Array.isArray(next.levels) && next.levels.length ? next.levels : structuredClone(demo.levels);
  next.areas = Array.isArray(next.areas) && next.areas.length ? next.areas : structuredClone(demo.areas);
  next.competencies = Array.isArray(next.competencies) ? next.competencies : [];
  next.competencies = next.competencies.map(c => ({ id: c.id || uid("competency"), text: c.text || c.description || "", materials: c.materials || c.material || "", notes: c.notes || "", areaId: c.areaId || next.areas[0].id, levelId: c.levelId || next.levels[0].id, prerequisites: Array.isArray(c.prerequisites) ? c.prerequisites : Array.isArray(c.prerequisiteIds) ? c.prerequisiteIds : [] }));
  return next;
}
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); $("saveState").textContent = "Gerade gespeichert"; setTimeout(() => $("saveState").textContent = "Lokal gespeichert", 900); }
function render() {
  $("titleInput").value = data.title || "Kompetenzraster";
  $("titleInput").disabled = presentationMode;
  $("headerTitle").textContent = data.title || "Kompetenzraster";
  document.body.classList.toggle("presentation-mode", presentationMode);
  setViewToggle("presentationToggleButton", presentationMode, "Präsentationsmodus");
  $("presentationToggleButton").hidden = presentationLocked;
  document.querySelectorAll(".editing-control").forEach(el => { el.hidden = presentationMode; });
  $("addAreaButton").hidden = presentationMode; $("addLevelButton").hidden = presentationMode;
  const board = $("board"); board.style.setProperty("--level-count", data.levels.length); board.replaceChildren();
  const corner = document.createElement("div"); corner.className = "board-header"; corner.textContent = "Kompetenzbereich"; board.append(corner);
  data.levels.forEach(level => { const head = document.createElement("div"); head.className = "board-header level level-label"; head.dataset.levelId = level.id; const span = document.createElement("span"); span.textContent = level.name; if (!presentationMode) { const edit = button("✎", "secondary", () => editText("level", level.id)); edit.title = "Kompetenzstufe bearbeiten"; head.append(span, edit); } else head.append(span); board.append(head); });
  data.areas.forEach((area, index) => {
    const label = document.createElement("div"); label.className = "area-label"; label.innerHTML = `<span></span>`; label.firstChild.textContent = area.name; if (!presentationMode) { const editArea = button("✎", "secondary", () => editText("area", area.id)); editArea.title = "Kompetenzbereich bearbeiten"; label.append(editArea); } board.append(label);
    data.levels.forEach(level => board.append(makeDropZone(area, level, index)));
  });
  drawDependencies();
}
function button(text, className, handler) { const b = document.createElement("button"); b.type = "button"; b.textContent = text; b.className = className || ""; b.addEventListener("click", handler); return b; }
function detail(label, value) { const section = document.createElement("div"); section.className = "card-detail"; const heading = document.createElement("strong"); heading.textContent = `${label}:`; section.append(heading, document.createTextNode(" ")); addLinkedText(section, value); return section; }
function addLinkedText(container, value) { String(value || "").split(/(https?:\/\/[^\s<]+)/g).forEach((part, index) => { if (index % 2) { const link = document.createElement("a"); link.href = part.replace(/[),.;!?]+$/, ""); link.textContent = link.href; link.target = "_blank"; link.rel = "noopener noreferrer"; container.append(link, document.createTextNode(part.slice(link.href.length))); } else { const lines = part.split("\n"); lines.forEach((line, lineIndex) => { if (lineIndex) container.append(document.createElement("br")); container.append(document.createTextNode(line)); }); } }); }
function makeDropZone(area, level, row) {
  const zone = document.createElement("div"); zone.className = `drop-zone ${row % 2 ? "shaded" : ""}`; zone.dataset.areaId = area.id; zone.dataset.levelId = level.id;
  const cards = data.competencies.filter(c => c.areaId === area.id && c.levelId === level.id);
  cards.forEach(c => zone.append(makeCard(c)));
  if (!presentationMode) zone.append(button("+ Kompetenz", "add-competency", () => openCompetency(null, area.id, level.id))); zone.classList.toggle("empty", cards.length === 0);
  ["dragover", "drop", "dragleave"].forEach(type => zone.addEventListener(type, onDropEvent)); return zone;
}
function makeCard(c) {
  const isDependencySource = dependencySelection?.role === "prerequisite" && dependencySelection.id === c.id;
  const isDependencyTarget = dependencySelection?.role === "target" && dependencySelection.id === c.id;
  const dependencyMode = dependencySelection !== null;
  const card = document.createElement("article"); card.className = `card ${isDependencySource ? "dependency-source" : ""} ${isDependencyTarget ? "dependency-selected-target" : ""} ${dependencyMode && !isDependencySource && !isDependencyTarget ? "dependency-target" : ""}`; card.draggable = !presentationMode; card.dataset.id = c.id; card.tabIndex = 0;
  let info = null; if (c.materials || c.notes) { card.classList.add("has-card-info"); info = document.createElement("div"); info.className = "card-info"; const details = button("ⓘ", "info-button", e => { e.stopPropagation(); openInfo(c); }); details.title = "Weitere Informationen anzeigen"; details.setAttribute("aria-label", details.title); info.append(details); }
  const text = document.createElement("span"); text.className = "card-text"; text.textContent = c.text || "Unbenannte Kompetenz"; card.append(text); if (info) card.append(info);
  const meta = document.createElement("div"); meta.className = "card-meta"; const deps = (c.prerequisites || []).length; if (deps) { const p = document.createElement("span"); p.className = "pill dependency"; p.textContent = `${deps} Voraussetzung${deps === 1 ? "" : "en"}`; meta.append(p); } if (isDependencySource) { const p = document.createElement("span"); p.className = "pill dependency-role source-role"; p.textContent = "Voraussetzung ausgewählt"; meta.append(p); } else if (isDependencyTarget) { const p = document.createElement("span"); p.className = "pill dependency-role target-role"; p.textContent = "Folge-Kompetenz ausgewählt"; meta.append(p); } else if (dependencyMode) { const p = document.createElement("span"); p.className = `pill dependency-role ${dependencySelection.role === "prerequisite" ? "target-role" : "source-role"}`; p.textContent = dependencySelection.role === "prerequisite" ? "Folge-Kompetenz auswählen" : "Voraussetzung auswählen"; meta.append(p); } if (meta.children.length) card.append(meta);
  if (!presentationMode) { const tools = document.createElement("div"); tools.className = "card-tools";
    const prerequisite = button("⇣", "card-tool dependency-tool", e => { e.stopPropagation(); startDependency(c.id, "target"); }); prerequisite.title = "Eine Voraussetzung für diese Kompetenz auswählen"; prerequisite.setAttribute("aria-label", prerequisite.title);
    const target = button("⇡", "card-tool target-tool", e => { e.stopPropagation(); startDependency(c.id, "prerequisite"); }); target.title = "Diese Kompetenz als Voraussetzung für die nächste auswählen"; target.setAttribute("aria-label", target.title);
    const edit = button("✎", "card-tool", e => { e.stopPropagation(); openCompetency(c.id); }); edit.title = "Kompetenz bearbeiten"; edit.setAttribute("aria-label", edit.title); tools.append(prerequisite, target, edit); card.append(tools); }
  card.addEventListener("click", () => { if (dependencySelection && dependencySelection.id !== c.id) { const sourceId = dependencySelection.role === "prerequisite" ? dependencySelection.id : c.id; const targetId = dependencySelection.role === "prerequisite" ? c.id : dependencySelection.id; addDependency(sourceId, targetId); } }); card.addEventListener("mouseenter", () => { if (dependencySelection && dependencySelection.id !== c.id) { dependencyPreviewId = c.id; drawDependencies(); } }); card.addEventListener("mouseleave", () => { if (dependencyPreviewId === c.id) { dependencyPreviewId = null; drawDependencies(); } }); card.addEventListener("dragstart", e => { draggedId = c.id; card.classList.add("dragging"); e.dataTransfer.effectAllowed = "move"; e.dataTransfer.setData("text/plain", c.id); }); card.addEventListener("dragend", () => { draggedId = null; card.classList.remove("dragging"); document.querySelectorAll(".drag-over").forEach(z => z.classList.remove("drag-over")); }); card.addEventListener("dblclick", () => openCompetency(c.id)); return card;
}
function onDropEvent(e) {
  if (presentationMode || [...(e.dataTransfer?.types || [])].includes("Files")) return;
  e.preventDefault();
  const zone = e.currentTarget;
  if (e.type === "dragover") { zone.classList.add("drag-over"); return; }
  if (e.type === "dragleave") { if (!zone.contains(e.relatedTarget)) zone.classList.remove("drag-over"); return; }
  zone.classList.remove("drag-over");
  const id = draggedId || e.dataTransfer.getData("text/plain");
  const c = data.competencies.find(x => x.id === id);
  if (!c) return;

  const targetCard = e.target.closest?.(".card");
  if (targetCard && !zone.contains(targetCard)) return;
  if (targetCard?.dataset.id === id) return;

  data.competencies = data.competencies.filter(x => x.id !== id);
  c.areaId = zone.dataset.areaId;
  c.levelId = zone.dataset.levelId;

  const targetId = targetCard?.dataset.id;
  let insertIndex = data.competencies.length;
  if (targetId) {
    const targetIndex = data.competencies.findIndex(x => x.id === targetId);
    if (targetIndex >= 0) {
      const targetRect = targetCard.getBoundingClientRect();
      insertIndex = targetIndex + (e.clientY >= targetRect.top + targetRect.height / 2 ? 1 : 0);
    }
  } else {
    const lastInZone = data.competencies.map((x, index) => ({ x, index })).filter(({ x }) => x.areaId === c.areaId && x.levelId === c.levelId).at(-1);
    if (lastInZone) insertIndex = lastInZone.index + 1;
  }
  data.competencies.splice(insertIndex, 0, c);
  save();
  render();
}
function startDependency(id, role) { if (presentationMode) return; dependencySelection = dependencySelection?.id === id && dependencySelection.role === role ? null : { id, role }; dependencyPreviewId = null; $("hint").textContent = dependencySelection ? dependencySelection.role === "prerequisite" ? "Schritt 1/2: Diese Kompetenz ist die Voraussetzung. Wähle jetzt die Folge-Kompetenz – der Pfeil zeigt dorthin." : "Schritt 1/2: Diese Kompetenz ist die Folge-Kompetenz. Wähle jetzt ihre Voraussetzung – der Pfeil zeigt anschließend hierhin." : "Drag-and-drop: Kompetenzen lassen sich zwischen den Zellen verschieben. ⇣ Voraussetzung für diese Kompetenz auswählen. ⇡ Diese Kompetenz als Voraussetzung für die nächste auswählen."; render(); }
function cancelDependency() { dependencySelection = null; dependencyPreviewId = null; $("hint").textContent = "Auswahl abgebrochen."; render(); }
function addDependency(sourceId, targetId) { if (sourceId === targetId) { alert("Eine Kompetenz kann nicht von sich selbst abhängen."); return; } const target = data.competencies.find(c => c.id === targetId); if (!target) return; if (target.prerequisites.includes(sourceId)) { dependencySelection = null; dependencyPreviewId = null; render(); return; } if (dependsOn(sourceId, targetId)) { alert("Diese Abhängigkeit würde einen Kreis erzeugen."); return; } target.prerequisites.push(sourceId); dependencySelection = null; dependencyPreviewId = null; save(); $("hint").textContent = "Abhängigkeit gespeichert. Nutze ⇣ oder ⇡ für die nächste."; render(); }
function dependsOn(startId, wantedId, seen = new Set()) { if (startId === wantedId) return true; if (seen.has(startId)) return false; seen.add(startId); const c = data.competencies.find(x => x.id === startId); return (c?.prerequisites || []).some(id => dependsOn(id, wantedId, seen)); }
function drawDependencies() { const board = $("board"); board.querySelector(".dependency-layer")?.remove(); $("dependencyToggleButton").setAttribute("aria-pressed", showDependencies); if (!showDependencies) return; const layer = document.createElementNS("http://www.w3.org/2000/svg", "svg"); layer.classList.add("dependency-layer"); layer.setAttribute("width", board.scrollWidth); layer.setAttribute("height", board.scrollHeight); layer.innerHTML = `<defs><marker id="dependency-arrow" markerWidth="13" markerHeight="13" refX="11" refY="6.5" markerUnits="userSpaceOnUse" orient="auto"><path d="M0,0 L13,6.5 L0,13 Z" fill="#754c92"></path></marker></defs>`; const boardRect = board.getBoundingClientRect(); for (const target of data.competencies) for (const prerequisiteId of target.prerequisites || []) { const sourceEl = board.querySelector(`[data-id="${CSS.escape(prerequisiteId)}"]`); const targetEl = board.querySelector(`[data-id="${CSS.escape(target.id)}"]`); if (!sourceEl || !targetEl) continue; const a = sourceEl.getBoundingClientRect(); const b = targetEl.getBoundingClientRect(); const x1 = a.left - boardRect.left + board.scrollLeft + a.width / 2; const y1 = a.top - boardRect.top + board.scrollTop + a.height / 2; const x2 = b.left - boardRect.left + board.scrollLeft + b.width / 2; const y2 = b.top - boardRect.top + board.scrollTop + b.height / 2; const dx = x2 - x1; const dy = y2 - y1; const distance = Math.max(1, Math.hypot(dx, dy)); const ux = dx / distance; const uy = dy / distance; const sourceEdge = Math.abs(ux) * a.width / 2 + Math.abs(uy) * a.height / 2; const targetEdge = Math.abs(ux) * b.width / 2 + Math.abs(uy) * b.height / 2; const startX = x1 + ux * (sourceEdge + 5); const startY = y1 + uy * (sourceEdge + 5); const endX = x2 - ux * (targetEdge + 13); const endY = y2 - uy * (targetEdge + 13); const path = document.createElementNS("http://www.w3.org/2000/svg", "path"); const bend = Math.max(35, Math.abs(endX - startX) * .3); path.setAttribute("d", `M ${startX} ${startY} C ${startX + (endX - startX) * .35} ${startY}, ${endX - (endX - startX) * .35} ${endY}, ${endX} ${endY}`); path.setAttribute("fill", "none"); path.setAttribute("stroke", "#754c92"); path.setAttribute("stroke-width", "3"); path.setAttribute("stroke-linecap", "round"); path.setAttribute("marker-end", "url(#dependency-arrow)"); layer.append(path); } board.append(layer); }
function drawDependencyArrow(layer, sourceEl, targetEl, preview = false) {
  const board = $("board"); const boardRect = board.getBoundingClientRect(); const a = sourceEl.getBoundingClientRect(); const b = targetEl.getBoundingClientRect(); const x1 = a.left - boardRect.left + board.scrollLeft + a.width / 2; const y1 = a.top - boardRect.top + board.scrollTop + a.height / 2; const x2 = b.left - boardRect.left + board.scrollLeft + b.width / 2; const y2 = b.top - boardRect.top + board.scrollTop + b.height / 2; const dx = x2 - x1; const dy = y2 - y1; const distance = Math.max(1, Math.hypot(dx, dy)); const ux = dx / distance; const uy = dy / distance; const sourceEdge = Math.abs(ux) * a.width / 2 + Math.abs(uy) * a.height / 2; const targetEdge = Math.abs(ux) * b.width / 2 + Math.abs(uy) * b.height / 2; const startX = x1 + ux * (sourceEdge + 5); const startY = y1 + uy * (sourceEdge + 5); const endX = x2 - ux * (targetEdge + 15); const endY = y2 - uy * (targetEdge + 15); const path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.setAttribute("d", `M ${startX} ${startY} C ${startX + (endX - startX) * .35} ${startY}, ${endX - (endX - startX) * .35} ${endY}, ${endX} ${endY}`); path.setAttribute("class", preview ? "dependency-preview" : ""); path.setAttribute("fill", "none"); path.setAttribute("stroke", "#754c92"); path.setAttribute("stroke-width", preview ? "4" : "3"); path.setAttribute("stroke-linecap", "round"); path.setAttribute("marker-end", "url(#dependency-arrow)"); layer.append(path);
}
function drawDependencies() { const board = $("board"); board.querySelector(".dependency-layer")?.remove(); $("dependencyToggleButton").setAttribute("aria-pressed", showDependencies); if (!showDependencies && !(dependencySelection && dependencyPreviewId)) return; const layer = document.createElementNS("http://www.w3.org/2000/svg", "svg"); layer.classList.add("dependency-layer"); layer.setAttribute("width", board.scrollWidth); layer.setAttribute("height", board.scrollHeight); layer.innerHTML = `<defs><marker id="dependency-arrow" markerWidth="16" markerHeight="16" refX="13" refY="8" markerUnits="userSpaceOnUse" orient="auto"><path d="M0,0 L16,8 L0,16 Z" fill="#754c92"></path></marker></defs>`; if (showDependencies) for (const target of data.competencies) for (const prerequisiteId of target.prerequisites || []) { const sourceEl = board.querySelector(`[data-id="${CSS.escape(prerequisiteId)}"]`); const targetEl = board.querySelector(`[data-id="${CSS.escape(target.id)}"]`); if (sourceEl && targetEl) drawDependencyArrow(layer, sourceEl, targetEl); } if (dependencySelection && dependencyPreviewId) { const first = board.querySelector(`[data-id="${CSS.escape(dependencySelection.id)}"]`); const second = board.querySelector(`[data-id="${CSS.escape(dependencyPreviewId)}"]`); if (first && second) { const sourceEl = dependencySelection.role === "prerequisite" ? first : second; const targetEl = dependencySelection.role === "prerequisite" ? second : first; drawDependencyArrow(layer, sourceEl, targetEl, true); } } board.append(layer); }
function drawDependencyArrow(layer, sourceEl, targetEl, preview = false) {
  const board = $("board"); const boardRect = board.getBoundingClientRect(); const a = sourceEl.getBoundingClientRect(); const b = targetEl.getBoundingClientRect(); const x1 = a.left - boardRect.left + board.scrollLeft + a.width / 2; const y1 = a.top - boardRect.top + board.scrollTop + a.height / 2; const x2 = b.left - boardRect.left + board.scrollLeft + b.width / 2; const y2 = b.top - boardRect.top + board.scrollTop + b.height / 2; const dx = x2 - x1; const dy = y2 - y1; const distance = Math.max(1, Math.hypot(dx, dy)); const ux = dx / distance; const uy = dy / distance; const sourceEdge = Math.abs(ux) * a.width / 2 + Math.abs(uy) * a.height / 2; const targetEdge = Math.abs(ux) * b.width / 2 + Math.abs(uy) * b.height / 2; const gap = 4; const startX = x1 + ux * (sourceEdge + gap); const startY = y1 + uy * (sourceEdge + gap); const endX = x2 - ux * (targetEdge + gap); const endY = y2 - uy * (targetEdge + gap); const path = document.createElementNS("http://www.w3.org/2000/svg", "path"); const d = Math.abs(dx) >= Math.abs(dy) ? "M " + startX + " " + startY + " C " + (startX + endX) / 2 + " " + startY + ", " + (startX + endX) / 2 + " " + endY + ", " + endX + " " + endY : "M " + startX + " " + startY + " C " + startX + " " + (startY + endY) / 2 + ", " + endX + " " + (startY + endY) / 2 + ", " + endX + " " + endY; path.setAttribute("d", d); path.setAttribute("class", preview ? "dependency-preview" : ""); path.setAttribute("fill", "none"); path.setAttribute("stroke", "#754c92"); path.setAttribute("stroke-width", preview ? "4" : "3"); path.setAttribute("stroke-linecap", "round"); path.setAttribute("marker-end", "url(#dependency-arrow)"); layer.append(path);
}
function drawDependencyArrow(layer, sourceEl, targetEl, preview = false) {
  const board = $("board"); const boardRect = board.getBoundingClientRect(); const a = sourceEl.getBoundingClientRect(); const b = targetEl.getBoundingClientRect(); const sourceZone = sourceEl.closest(".drop-zone"); const targetZone = targetEl.closest(".drop-zone"); const x1 = a.left - boardRect.left + board.scrollLeft + a.width / 2; const y1 = a.top - boardRect.top + board.scrollTop + a.height / 2; const x2 = b.left - boardRect.left + board.scrollLeft + b.width / 2; const y2 = b.top - boardRect.top + board.scrollTop + b.height / 2; const sourceRight = a.right - boardRect.left + board.scrollLeft + 4; const sourceLeft = a.left - boardRect.left + board.scrollLeft - 4; const targetRight = b.right - boardRect.left + board.scrollLeft + 4; const targetLeft = b.left - boardRect.left + board.scrollLeft - 4; const sameColumn = sourceZone && targetZone && Math.abs(sourceZone.getBoundingClientRect().left - targetZone.getBoundingClientRect().left) < 2; let d;
  if (sameColumn) { const laneX = Math.max(a.right, b.right) - boardRect.left + board.scrollLeft + 10; d = "M " + sourceRight + " " + y1 + " L " + laneX + " " + y1 + " L " + laneX + " " + y2 + " L " + targetRight + " " + y2; } else { const toRight = x2 > x1; const startX = toRight ? sourceRight : sourceLeft; const endX = toRight ? targetLeft : targetRight; const laneX = (startX + endX) / 2; d = "M " + startX + " " + y1 + " L " + laneX + " " + y1 + " L " + laneX + " " + y2 + " L " + endX + " " + y2; }
  const path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.setAttribute("d", d); path.setAttribute("class", preview ? "dependency-preview" : ""); path.setAttribute("fill", "none"); path.setAttribute("stroke", "#754c92"); path.setAttribute("stroke-width", preview ? "4" : "3"); path.setAttribute("stroke-linecap", "round"); path.setAttribute("stroke-linejoin", "round"); path.setAttribute("marker-end", "url(#dependency-arrow)"); layer.append(path);
}
function drawDependencyArrow(layer, sourceEl, targetEl, preview = false) {
  const board = $("board"); const boardRect = board.getBoundingClientRect(); const a = sourceEl.getBoundingClientRect(); const b = targetEl.getBoundingClientRect(); const x1 = a.left - boardRect.left + board.scrollLeft + a.width / 2; const y1 = a.top - boardRect.top + board.scrollTop + a.height / 2; const x2 = b.left - boardRect.left + board.scrollLeft + b.width / 2; const y2 = b.top - boardRect.top + board.scrollTop + b.height / 2; const path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.setAttribute("d", "M " + x1 + " " + y1 + " L " + x2 + " " + y2); path.setAttribute("class", preview ? "dependency-preview" : ""); path.setAttribute("fill", "none"); path.setAttribute("stroke", "#754c92"); path.setAttribute("stroke-opacity", preview ? ".65" : ".5"); path.setAttribute("stroke-width", preview ? "4" : "3"); path.setAttribute("stroke-linecap", "round"); path.setAttribute("marker-end", "url(#dependency-arrow)"); layer.append(path);
}
function scheduleDraw() { cancelAnimationFrame(drawFrame); drawFrame = requestAnimationFrame(drawDependencies); }
function openCompetency(id, areaId, levelId) { if (presentationMode) return; const c = data.competencies.find(x => x.id === id); $("competencyId").value = id || ""; $("competencyDialogTitle").textContent = c ? "Kompetenz bearbeiten" : "Kompetenz hinzufügen"; $("competencyText").value = c?.text || ""; $("competencyMaterials").value = c?.materials || ""; $("competencyNotes").value = c?.notes || ""; $("deleteCompetencyButton").hidden = !c; $("competencyForm").dataset.areaId = areaId || c?.areaId || data.areas[0].id; $("competencyForm").dataset.levelId = levelId || c?.levelId || data.levels[0].id; renderPrerequisites(c); $("competencyDialog").showModal(); $("competencyText").focus(); }
function openInfo(c) { $("detailDialogContext").textContent = c.text || "Unbenannte Kompetenz"; const content = $("detailDialogContent"); content.replaceChildren(); [["Material", c.materials], ["Bemerkung", c.notes]].filter(([, value]) => value).forEach(([label, value]) => { const section = document.createElement("section"); section.className = "detail-section"; const heading = document.createElement("h3"); heading.textContent = label; const text = document.createElement("div"); addLinkedText(text, value); section.append(heading, text); content.append(section); }); $("detailDialog").showModal(); }
document.querySelectorAll("[data-dialog-cancel]").forEach(button => button.addEventListener("click", () => button.closest("dialog").close()));
function renderPrerequisites(current) { const list = $("prerequisiteList"); list.replaceChildren(); const selected = new Set(current?.prerequisites || []); data.competencies.filter(c => c.id !== current?.id).forEach(c => { const label = document.createElement("label"); label.className = "prerequisite-option"; const input = document.createElement("input"); input.type = "checkbox"; input.value = c.id; input.checked = selected.has(c.id); const span = document.createElement("span"); span.textContent = c.text || "Unbenannte Kompetenz"; label.append(input, span); list.append(label); }); if (!list.children.length) list.textContent = "Lege zunächst weitere Kompetenzen an."; }
$("competencyForm").addEventListener("submit", e => { const form = e.currentTarget; if (e.submitter?.value === "cancel") { e.preventDefault(); $("competencyDialog").close(); return; } e.preventDefault(); const id = $("competencyId").value || uid("competency"); const existing = data.competencies.find(c => c.id === id); const c = existing || { id }; Object.assign(c, { text: $("competencyText").value.trim(), materials: $("competencyMaterials").value.trim(), notes: $("competencyNotes").value.trim(), areaId: form.dataset.areaId, levelId: form.dataset.levelId, prerequisites: [...document.querySelectorAll("#prerequisiteList input:checked")].map(x => x.value) }); if (!existing) data.competencies.push(c); save(); $("competencyDialog").close(); render(); });
$("deleteCompetencyButton").addEventListener("click", () => { const id = $("competencyId").value; if (!id || !confirm("Kompetenz wirklich löschen?")) return; data.competencies = data.competencies.filter(c => c.id !== id).map(c => ({ ...c, prerequisites: c.prerequisites.filter(p => p !== id) })); save(); $("competencyDialog").close(); render(); });
function editText(kind, id) { if (presentationMode) return; const collection = kind === "area" ? data.areas : data.levels; const item = collection.find(x => x.id === id); $("textDialogTitle").textContent = kind === "area" ? "Kompetenzbereich bearbeiten" : "Kompetenzstufe bearbeiten"; $("textInput").value = item.name; $("textForm").dataset.kind = kind; $("textForm").dataset.id = id; $("deleteTextButton").hidden = collection.length <= 1; $("textDialog").showModal(); $("textInput").focus(); }
$("textForm").addEventListener("submit", e => { const f = e.currentTarget; if (e.submitter?.value === "cancel") { e.preventDefault(); $("textDialog").close(); return; } e.preventDefault(); const collection = f.dataset.kind === "area" ? data.areas : data.levels; const item = collection.find(x => x.id === f.dataset.id); if (item) item.name = $("textInput").value.trim() || item.name; save(); $("textDialog").close(); render(); });
function deleteDimension(kind, id) { const collection = kind === "area" ? data.areas : data.levels; if (collection.length <= 1) return; const item = collection.find(x => x.id === id); if (!item || !confirm(`${kind === "area" ? "Kompetenzbereich" : "Kompetenzstufe"} „${item.name}“ wirklich löschen? Die zugehörigen Kompetenzen werden ebenfalls gelöscht.`)) return; const removedIds = new Set(data.competencies.filter(c => c[kind + "Id"] === id).map(c => c.id)); data.competencies = data.competencies.filter(c => !removedIds.has(c.id)).map(c => ({ ...c, prerequisites: c.prerequisites.filter(p => !removedIds.has(p)) })); if (kind === "area") data.areas = data.areas.filter(x => x.id !== id); else data.levels = data.levels.filter(x => x.id !== id); save(); if ($("textDialog").open) $("textDialog").close(); render(); }
$("deleteTextButton").addEventListener("click", () => deleteDimension($("textForm").dataset.kind, $("textForm").dataset.id));
$("addAreaButton").addEventListener("click", () => { const name = prompt("Name des Kompetenzbereichs:", "Neuer Kompetenzbereich"); if (!name?.trim()) return; data.areas.push({ id: uid("area"), name: name.trim() }); save(); render(); });
$("addLevelButton").addEventListener("click", () => { const name = prompt("Name der Kompetenzstufe:", `Level ${data.levels.length + 1}`); if (!name?.trim()) return; data.levels.push({ id: uid("level"), name: name.trim() }); save(); render(); });
$("titleInput").addEventListener("change", e => { data.title = e.target.value.trim() || "Kompetenzraster"; save(); });
function makeMarkdown() { const esc = s => String(s || "").replace(/([\\|])/g, "\\$1").replace(/\n/g, "<br>"); const headers = data.levels.map(l => ` ${esc(l.name)} `).join("|"); const separator = data.levels.map(() => "---").join("|"); const rows = data.areas.map(a => { const cells = data.levels.map(l => data.competencies.filter(c => c.areaId === a.id && c.levelId === l.id).map(c => `${esc(c.text)}${c.materials ? `<br><small>Material: ${esc(c.materials)}</small>` : ""}`).join("<br><br>")); return `| ${esc(a.name)} | ${cells.join(" | ")} |`; }).join("\n"); return `# ${data.title || "Kompetenzraster"}\n\n| Kompetenzbereich |${headers}|\n|---|${separator}|\n${rows}\n`; }
function bytesToBase64(bytes) { let binary = ""; for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
function base64ToBytes(value) { const binary = atob(value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - value.length % 4) % 4)); return Uint8Array.from(binary, char => char.charCodeAt(0)); }
async function encodeRaster() { const json = JSON.stringify(data); if ("CompressionStream" in window) { const stream = new Blob([json]).stream().pipeThrough(new CompressionStream("deflate-raw")); return `d1.${bytesToBase64(new Uint8Array(await new Response(stream).arrayBuffer()))}`; } return `p1.${bytesToBase64(new TextEncoder().encode(json))}`; }
async function decodeRaster(payload) { const [version, value] = payload.split(".", 2); const bytes = base64ToBytes(value); if (version === "d1" && "DecompressionStream" in window) { const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream("deflate-raw")); return JSON.parse(await new Response(stream).text()); } if (version === "p1") return JSON.parse(new TextDecoder().decode(bytes)); throw new Error("Unbekanntes Linkformat"); }
async function makeRasterLink(readonlyLink = false) { const url = new URL(location.href); url.hash = `raster=${await encodeRaster()}${readonlyLink ? "&readonly=1" : ""}`; return url.href; }
async function loadRasterFromLink() { const params = new URLSearchParams(location.hash.slice(1)); const payload = params.get("raster"); if (!payload) return; try { presentationLocked = params.get("readonly") === "1"; presentationMode = presentationLocked; data = normalize(await decodeRaster(payload)); save(); render(); $("saveState").textContent = presentationMode ? "Readonly-Präsentationsansicht geladen" : "Link-Raster geladen"; } catch { alert("Der Raster-Link konnte nicht gelesen werden."); } }
async function exportData(format) { if (format === "html") download("kompetenzraster.html", makeHtml(), "text/html"); else if (format === "markdown") download("kompetenzraster.md", makeMarkdown(), "text/markdown"); else if (format === "json") download("kompetenzraster.json", JSON.stringify(data, null, 2), "application/json"); else if (format === "link") { const link = await makeRasterLink($("readonlyLink").checked); const note = "Der Link enthält den momentanen Zustand des Kompetenzrasters. Spätere Änderungen sind unter diesem Link nicht erreichbar.\n\nBeachte außerdem: Browser erlauben unterschiedlich lange Links. Bei einem sehr großen Kompetenzraster kann der Link zu lang werden und sich möglicherweise nicht mehr öffnen lassen."; try { await navigator.clipboard.writeText(link); alert(`${note}\n\nDer Raster-Link wurde in die Zwischenablage kopiert.`); } catch { prompt(`${note}\n\nRaster-Link zum Kopieren:`, link); } } $("exportDialog").close(); }
$("exportButton").addEventListener("click", () => $("exportDialog").showModal()); document.querySelectorAll("[data-export]").forEach(option => option.addEventListener("click", () => exportData(option.dataset.export)));
function hasRasterContent() { return data.competencies.length > 0 || data.title !== demo.title || data.areas.length !== demo.areas.length || data.levels.length !== demo.levels.length || data.areas.some((area, index) => area.name !== demo.areas[index]?.name) || data.levels.some((level, index) => level.name !== demo.levels[index]?.name); }
async function importJsonFile(file) { if (presentationMode || !file) return; if (!file.name.toLowerCase().endsWith(".json") && file.type !== "application/json") { alert("Bitte lege eine JSON-Datei ab."); return; } if (hasRasterContent() && !confirm("Das aktuelle Kompetenzraster enthält bereits Daten. Beim Import werden sie ersetzt. Fortfahren?")) return; try { data = normalize(JSON.parse(await file.text())); presentationMode = false; presentationLocked = false; save(); render(); } catch { alert("Die JSON-Datei konnte nicht gelesen werden."); } }
$("importButton").addEventListener("click", () => $("importFile").click()); $("importFile").addEventListener("change", async e => { await importJsonFile(e.target.files[0]); e.target.value = ""; });
function isFileDrag(e) { return [...(e.dataTransfer?.types || [])].includes("Files"); }
function clearFileDragState() { fileDragDepth = 0; document.body.classList.remove("file-drag-over"); }
document.addEventListener("dragenter", e => { if (!isFileDrag(e) || presentationMode) return; e.preventDefault(); fileDragDepth += 1; document.body.classList.add("file-drag-over"); });
document.addEventListener("dragover", e => { if (!isFileDrag(e)) return; e.preventDefault(); if (!presentationMode) document.body.classList.add("file-drag-over"); });
document.addEventListener("dragleave", e => { if (!isFileDrag(e) || presentationMode) return; fileDragDepth -= 1; if (fileDragDepth <= 0) clearFileDragState(); });
document.addEventListener("drop", e => { if (!isFileDrag(e)) return; e.preventDefault(); clearFileDragState(); importJsonFile(e.dataTransfer.files[0]); });
$("newButton").addEventListener("click", () => { if (!confirm("Das aktuelle Raster verwerfen und ein neues beginnen?")) return; data = structuredClone(demo); save(); render(); });
function download(name, content, type) { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([content], { type })); a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
function makeHtml() { const esc = s => String(s || "").replace(/[&<>\"]/g, x => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[x])); const rich = s => esc(s).replace(/(https?:\/\/[^\s<]+)/g, '<a href="$1">$1</a>').replace(/\n/g, "<br>"); const headers = data.levels.map(l => `<th>${esc(l.name)}</th>`).join(""); const rows = data.areas.map(a => `<tr><th>${esc(a.name)}</th>${data.levels.map(l => `<td>${data.competencies.filter(c => c.areaId === a.id && c.levelId === l.id).map(c => `<p>${rich(c.text)}</p>${c.materials ? `<small>Material: ${rich(c.materials)}</small>` : ""}${c.notes ? `<small>Bemerkungen: ${rich(c.notes)}</small>` : ""}`).join("")}</td>`).join("")}</tr>`).join(""); return `<!doctype html><meta charset="utf-8"><title>${esc(data.title)}</title><style>body{font:15px system-ui;color:#183344}table{border-collapse:collapse;width:100%}th,td{border:1px solid #c7d4da;padding:10px;vertical-align:top}thead th{background:#c6d5dd}tbody tr:nth-child(odd){background:#f0f4f6}th:first-child{text-align:left}p{margin:0 0 9px}small{display:block;color:#647784;margin-top:5px}</style><h1>${esc(data.title)}</h1><table><thead><tr><th>Kompetenzbereich</th>${headers}</tr></thead><tbody>${rows}</tbody></table>`; }
function setViewToggle(id, value, label) { $(id).classList.toggle("active", value); $(id).setAttribute("aria-pressed", value); $(id).title = `${label} ${value ? "ausblenden" : "anzeigen"}`; $(id).setAttribute("aria-label", $(id).title); }
$("dependencyToggleButton").addEventListener("click", () => { showDependencies = !showDependencies; setViewToggle("dependencyToggleButton", showDependencies, "Abhängigkeiten"); drawDependencies(); });
$("presentationToggleButton").addEventListener("click", () => { presentationMode = !presentationMode; if (presentationMode) { dependencySelection = null; dependencyPreviewId = null; } setViewToggle("presentationToggleButton", presentationMode, "Präsentationsmodus"); render(); });
$("helpButton").addEventListener("click", () => $("helpDialog").showModal());
document.addEventListener("keydown", e => { if (e.key === "Escape" && dependencySelection) { e.preventDefault(); cancelDependency(); } });
document.addEventListener("click", e => { if (dependencySelection && !e.target.closest(".card")) cancelDependency(); });
$("board").addEventListener("scroll", scheduleDraw); window.addEventListener("resize", scheduleDraw);
render();
loadRasterFromLink();
